### ISSUE TITLE
Error creating query - **TypeError: method() takes 1 positional argument but 2 were given**

### ISSUE THREAD

**Issue by eduardoblucas** [googleads/googleads-bidmanager-examples#17] opened 2021-01-26 16:02 UTC
query_test = {
        "kind": "doubleclickbidmanager#query",
        "metadata": {
            "dataRange": "ALL_TIME",
            "format": "CSV",
            "googleCloudStoragePathForLatestReport": "",
            "googleDrivePathForLatestReport": "",
            "latestReportRunTimeMs": "",
            "locale": "",
            "reportCount": 0,
            "running": False,
            "sendNotification": False,
            "shareEmailAddress": [
                ""
            ],
            "title": ""
        },
        "params": {
            "filters": [
                {}
            ],
            "groupBys": [
                "FILTER_ACTIVE_VIEW_EXPECTED_VIEWABILITY"
            ],
            "includeInviteData": False,
            "metrics": [
                "METRIC_ACTIVE_VIEW_AUDIBLE_VISIBLE_ON_COMPLETE_IMPRESSIONS"
            ],
            "type": "TYPE_ACTIVE_GRP"
        },
        "queryId": "",
        "reportDataEndTimeMs": "",
        "reportDataStartTimeMs": "",
        "schedule": {
            "endTimeMs": "",
            "frequency": "DAILY",
            "nextRunMinuteOfDay": 0,
            "nextRunTimezoneCode": ""
        },
        "timezoneCode": ""
    }
    createdQuery = service.queries().createquery(query_test)
    print(createdQuery)

**Comment by tmulchay** [comment] 2021-01-26 21:10
Hi,

I believe this error is being caused by not specifying the parameter in the `createquery` call. This should be fixed by changing `createdQuery = service.queries().createquery(query_test)` to `createdQuery = service.queries().createquery(body=query_test)`

Thank you,
Trevor Mulchay, DBM API Team

**Comment by eduardoblucas** [comment] 2021-01-27 10:34
Thank you it worked

**Closed as completed** 2021-01-28 16:05 UTC
